### ISSUE TITLE
BUG: Cannot handle directories with spaces in it

### ISSUE THREAD

**Issue by scottbrown** [brianp/muxed#11]
I know, it's bad form to have spaces in directory names.  But when I used one of my existing tmuxinator configuration files that opens up a directory with spaces in it, muxed incorrectly parses only the first word instead of the entire string.

Config:
```Yaml
# ~/.tmuxinator/jps-ledger.yml

name: jps-ledger
root: ~/JustPlainSimple Technologies Inc./financials/ledgers
...
```

Output:
```
cd ~/JustPlainSimple Technologies Inc./financials/ledgers
git status
greenhole:Downloads scott$ cd ~/JustPlainSimple Technologies Inc./financials/ledgers
git status
-bash: cd: /Users/scott/JustPlainSimple: No such file or directory
greenhole:Downloads scott$ git status
fatal: Not a git repository (or any of the parent directories): .git
greenhole:Downloads scott$
```
