### ISSUE TITLE
Quoting root dirs causes `~/` to stop working

### ISSUE THREAD

**Issue by brianp** [brianp/muxed#21]
The unix command `cd "~/"` does not work. When double quoted you have to use variables such as `cd "$HOME"`.

This isn't an ideal user experience. I want to be able to define `root: ~/`. A solution would be to handle root values with spaces differently then without spaces, although this means `root: ~/Dir With Space/project` would still fail. Maybe converting any usage of `~/` behind the scenes to `$HOME`?

Regression from #11

Example broken config:
```yaml
root: "~/"
windows:
  - editor:
      layout: "main-vertical"
      panes: ["vi", "ls -alh"]"
```
