### ISSUE TITLE
Add a Pre command for all windows

### ISSUE THREAD

**Issue by brianp** [brianp/muxed#3]
The `pre` option should accept a system command to execute. This will be executed before any of the window specific commands are executed.

It should exist at the root of the config file as such:
```yaml
root: "~/"
pre: "rbenv shell 2.2.0"
windows:
  - editor:
      layout: "main-vertical"
      panes: ["vi", "ls -alh"]
  - processes: "ls /proc"
  - logs: "tail -f /var/log/dmesg"
```
