### ISSUE TITLE
Snapshot is interpreting single pain windows weird

### ISSUE THREAD

**Issue by brianp** [brianp/muxed#31]
## System Info
OS: Mac OSX 10.14.3
Muxed Version: MASTER @ b3a0703b58ebca912911595a5962726417bdef9a

## Description
Snapshot is outputting config files where single pane windows are being written like multi-pane windows. They include `active` options (which seems like a bug), `layout`, and `panes`.
A hand written config like:
```
windows:
  - make: ''
  - vim: vim .
  - bash: ''
```

Will produce a snapshot config like:
```
windows:.                         
  -                              
    make:                        
      active: true                
      layout: "5ad5,119x32,0,0,35"
      panes:                     
        - ""                      
  -                              
    vim:                         
      active: false               
      layout: "5ad6,119x32,0,0,36"
      panes:                     
        - vim .                   
  -                              
    bash:.                        
      active: false               
      layout: "5ad7,119x32,0,0,37"
      panes:                
        - ""                      
```

This seems to lead into additional problems when executing the snapshot config. It may be trying to send commands to the wrong pane? I'm not entirely sure yet. But if a window only has 1 pain, we should avoid writing layout and pane information and use the shorthand syntax. (Although we still need a way to signify `active` for single pane windows.)

## Questions
- What to do about active?
- Is a single pane still not considered the 0 indexed pane for a window?

## Steps to reproduce

- Open a tmux session with a single pane window
- Execute a command in that window. `tail -f /usr/logs/system.log`
- snapshot the session `muxed snapshot -t 0 test`
- re-run the session `muxed test`

#### Expected
A single window session with a log tail running

#### Actual
A single window session with nothing running
